/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiAppEmptyState: typeof import('./components/ui/AppEmptyState.vue')['default']
    UiAppIcon: typeof import('./components/ui/AppIcon.vue')['default']
    UiAppPageLoader: typeof import('./components/ui/AppPageLoader.vue')['default']
    UiAppSkeleton: typeof import('./components/ui/AppSkeleton.vue')['default']
    UiAppToast: typeof import('./components/ui/AppToast.vue')['default']
    UiThemeToggle: typeof import('./components/ui/ThemeToggle.vue')['default']
  }
}
